### ISSUE TITLE
segfault when querying non-existent internal job id

### ISSUE THREAD

**Issue by keithj** [VertebrateResequencing/wr#139]
````
$ wr version                  
v0.14.0-0-g3793108

$ wr status -e -i i-dont-exist -y
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xbfc994]

goroutine 1 [running]:
github.com/VertebrateResequencing/wr/cmd.glob..func17(0x13efe60, 0xc4203baec0, 0x0, 0x4)
        /nfs/users/nfs_s/sb10/src/go/src/github.com/VertebrateResequencing/wr/cmd/status.go:249 +0xb44
github.com/VertebrateResequencing/wr/vendor/github.com/spf13/cobra.(*Command).execute(0x13efe60, 0xc4203bae80, 0x4, 0x4, 0x13efe60, 0xc4203bae80)
        /nfs/users/nfs_s/sb10/src/go/src/github.com/VertebrateResequencing/wr/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/VertebrateResequencing/wr/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x13ef9a0, 0xbf0d0e, 0x13ef9a0, 0xc4204fbf20)
        /nfs/users/nfs_s/sb10/src/go/src/github.com/VertebrateResequencing/wr/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/VertebrateResequencing/wr/vendor/github.com/spf13/cobra.(*Command).Execute(0x13ef9a0, 0x403e4c, 0xc4200280b8)
        /nfs/users/nfs_s/sb10/src/go/src/github.com/VertebrateResequencing/wr/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/VertebrateResequencing/wr/cmd.Execute()
        /nfs/users/nfs_s/sb10/src/go/src/github.com/VertebrateResequencing/wr/cmd/root.go:75 +0x2d
main.main()
        /nfs/users/nfs_s/sb10/src/go/src/github.com/VertebrateResequencing/wr/main.go:120 +0x9c
````

**Comment by sb10** [comment]
Already fixed in a pull request you reviewed ;)

**Comment by keithj** [comment]
Ah, yes! My head was completely in the data delivery project when I opened this.
